// angular-frontend/src/app/pages/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

interface Campaign {
  id: number;
  name: string;
  status: string;
  createdAt: Date;
}

@Component({
  selector: 'app-home',
  template: `
    <div class="p-8 max-w-[1280px] mx-auto w-full">
      <!-- Welcome Section -->
      <div class="mb-12 text-center">
        <h1 class="text-4xl font-bold text-gray-900 mb-4">
          Welcome to Campaign AI Gen
        </h1>
        <p class="text-xl text-gray-600 max-w-2xl mx-auto">
          Your AI-powered marketing platform for creating campaigns, catalogs, and content instantly
        </p>
      </div>

      <!-- Quick Creation Section -->
      <div class="mb-12">
        <mat-card class="p-8">
          <mat-card-header>
            <mat-card-title class="text-2xl font-semibold text-gray-900">
              Quick Campaign Creation
            </mat-card-title>
            <mat-card-subtitle class="text-gray-600 mt-2">
              Enter a prompt to instantly generate marketing assets
            </mat-card-subtitle>
          </mat-card-header>
          
          <mat-card-content class="mt-6">
            <div class="flex gap-4">
              <mat-form-field class="flex-1" appearance="outline">
                <mat-label>Describe your marketing campaign...</mat-label>
                <textarea 
                  matInput 
                  [(ngModel)]="campaignPrompt"
                  placeholder="e.g., Create a summer sale campaign for wireless headphones targeting young professionals"
                  rows="3"
                ></textarea>
              </mat-form-field>
              <div class="flex flex-col gap-2">
                <button 
                  mat-raised-button 
                  color="primary"
                  [disabled]="!campaignPrompt.trim()"
                  (click)="handleStartCampaign()"
                  class="px-8 py-3"
                >
                  <mat-icon>auto_awesome</mat-icon>
                  Generate
                </button>
                <button 
                  mat-stroked-button
                  (click)="router.navigate(['/campaign-generator'])"
                  class="px-8 py-2"
                >
                  Advanced Setup
                </button>
              </div>
            </div>
          </mat-card-content>
        </mat-card>
      </div>

      <!-- Recent Campaigns -->
      <div class="mb-12">
        <div class="flex justify-between items-center mb-6">
          <h2 class="text-2xl font-semibold text-gray-900">Recent Campaigns</h2>
          <div class="flex gap-4">
            <mat-form-field appearance="outline" class="w-64">
              <mat-label>Search campaigns...</mat-label>
              <input matInput [(ngModel)]="searchQuery" placeholder="Search...">
              <mat-icon matSuffix>search</mat-icon>
            </mat-form-field>
            <mat-form-field appearance="outline">
              <mat-label>Filter</mat-label>
              <mat-select [(ngModel)]="filterType">
                <mat-option value="all">All</mat-option>
                <mat-option value="active">Active</mat-option>
                <mat-option value="completed">Completed</mat-option>
                <mat-option value="draft">Draft</mat-option>
              </mat-select>
            </mat-form-field>
          </div>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6" *ngIf="!isLoading; else loadingTemplate">
          <mat-card 
            *ngFor="let campaign of filteredCampaigns" 
            class="cursor-pointer hover:shadow-lg transition-shadow"
            (click)="openCampaign(campaign)"
          >
            <mat-card-header>
              <mat-card-title>{{ campaign.name }}</mat-card-title>
              <mat-card-subtitle>{{ campaign.status | titlecase }}</mat-card-subtitle>
            </mat-card-header>
            <mat-card-content>
              <p class="text-gray-600">Created {{ campaign.createdAt | date:'short' }}</p>
            </mat-card-content>
            <mat-card-actions>
              <button mat-button color="primary">Open</button>
              <button mat-button>Share</button>
            </mat-card-actions>
          </mat-card>
        </div>

        <ng-template #loadingTemplate>
          <div class="flex justify-center py-12">
            <mat-spinner></mat-spinner>
          </div>
        </ng-template>

        <div *ngIf="filteredCampaigns.length === 0 && !isLoading" class="text-center py-12">
          <mat-icon class="text-6xl text-gray-400 mb-4">folder_open</mat-icon>
          <h3 class="text-xl font-medium text-gray-600 mb-2">No campaigns found</h3>
          <p class="text-gray-500">Create your first campaign to get started!</p>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .p-8 { padding: 2rem; }
    .max-w-[1280px] { max-width: 1280px; }
    .mx-auto { margin-left: auto; margin-right: auto; }
    .w-full { width: 100%; }
    .mb-12 { margin-bottom: 3rem; }
    .mb-6 { margin-bottom: 1.5rem; }
    .mb-4 { margin-bottom: 1rem; }
    .mb-2 { margin-bottom: 0.5rem; }
    .mt-6 { margin-top: 1.5rem; }
    .mt-2 { margin-top: 0.5rem; }
    .text-center { text-align: center; }
    .text-4xl { font-size: 2.25rem; }
    .text-2xl { font-size: 1.5rem; }
    .text-xl { font-size: 1.25rem; }
    .text-6xl { font-size: 4rem; }
    .font-bold { font-weight: 700; }
    .font-semibold { font-weight: 600; }
    .font-medium { font-weight: 500; }
    .text-gray-900 { color: rgb(17 24 39); }
    .text-gray-600 { color: rgb(75 85 99); }
    .text-gray-500 { color: rgb(107 114 128); }
    .text-gray-400 { color: rgb(156 163 175); }
    .max-w-2xl { max-width: 42rem; }
    .flex { display: flex; }
    .flex-1 { flex: 1; }
    .flex-col { flex-direction: column; }
    .gap-4 { gap: 1rem; }
    .gap-6 { gap: 1.5rem; }
    .gap-2 { gap: 0.5rem; }
    .justify-between { justify-content: space-between; }
    .justify-center { justify-content: center; }
    .items-center { align-items: center; }
    .px-8 { padding-left: 2rem; padding-right: 2rem; }
    .py-3 { padding-top: 0.75rem; padding-bottom: 0.75rem; }
    .py-2 { padding-top: 0.5rem; padding-bottom: 0.5rem; }
    .py-12 { padding-top: 3rem; padding-bottom: 3rem; }
    .w-64 { width: 16rem; }
    .grid { display: grid; }
    .grid-cols-1 { grid-template-columns: repeat(1, minmax(0, 1fr)); }
    .cursor-pointer { cursor: pointer; }
    .hover\\:shadow-lg:hover { box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05); }
    .transition-shadow { transition-property: box-shadow; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 150ms; }

    @media (min-width: 768px) {
      .md\\:grid-cols-2 { grid-template-columns: repeat(2, minmax(0, 1fr)); }
    }

    @media (min-width: 1024px) {
      .lg\\:grid-cols-3 { grid-template-columns: repeat(3, minmax(0, 1fr)); }
    }
  `]
})
export class HomeComponent implements OnInit {
  campaignPrompt = '';
  searchQuery = '';
  filterType = 'all';
  campaigns: Campaign[] = [];
  isLoading = false;

  constructor(
    public router: Router,
    private http: HttpClient
  ) {}

  ngOnInit() {
    this.loadCampaigns();
  }

  loadCampaigns() {
    this.isLoading = true;
    // Mock data for now - replace with actual API call
    setTimeout(() => {
      this.campaigns = [
        { id: 1, name: 'Summer Sale Campaign', status: 'active', createdAt: new Date() },
        { id: 2, name: 'Product Launch', status: 'completed', createdAt: new Date() },
        { id: 3, name: 'Holiday Promotion', status: 'draft', createdAt: new Date() }
      ];
      this.isLoading = false;
    }, 1000);
  }

  get filteredCampaigns() {
    return this.campaigns.filter(campaign => {
      const matchesSearch = campaign.name.toLowerCase().includes(this.searchQuery.toLowerCase());
      const matchesFilter = this.filterType === 'all' || campaign.status === this.filterType;
      return matchesSearch && matchesFilter;
    });
  }

  handleStartCampaign() {
    if (this.campaignPrompt.trim()) {
      localStorage.setItem('campaignPrompt', this.campaignPrompt.trim());
      this.router.navigate(['/canvas']);
    }
  }

  openCampaign(campaign: Campaign) {
    this.router.navigate(['/canvas', campaign.id]);
  }
}

// client/src/pages/home.tsx
import { Link, useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { 
  Plus, 
  Search, 
  Filter, 
  Grid3X3,
  List,
  TrendingUp,
  Sparkles,
  Zap,
  FileText
} from "lucide-react";
import { type Campaign } from "@shared/schema";

import MaterialHeader from "@/components/material-header";
import MaterialSidebar from "@/components/material-sidebar";
import MaterialProjectCard from "@/components/material-project-card";
import GlassBackground from "@/components/glass-background";

export default function Home() {
  const [searchQuery, setSearchQuery] = useState("");
  const [filterType, setFilterType] = useState("all");
  const [viewMode, setViewMode] = useState<"grid" | "list">("grid");
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [campaignPrompt, setCampaignPrompt] = useState("");
  const [, navigate] = useLocation();

  const { data: campaigns = [], isLoading } = useQuery<Campaign[]>({
    queryKey: ['/api/campaigns'],
  });

  const filteredCampaigns = campaigns.filter(campaign => {
    const matchesSearch = campaign.name.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesFilter = filterType === "all" || campaign.status === filterType;
    return matchesSearch && matchesFilter;
  });

  const handleStartCampaign = () => {
    if (campaignPrompt.trim()) {
      // Store the prompt in localStorage to pass to campaign generator
      localStorage.setItem('campaignPrompt', campaignPrompt.trim());
      // Navigate to campaign generator
      navigate('/campaign-generator');
    }
  };

  return (
    <div className="min-h-screen relative">
      <GlassBackground />
      <MaterialHeader onToggleSidebar={() => setSidebarOpen(!sidebarOpen)} />
      
      <div className="flex h-[calc(100vh-120px)]">
        <MaterialSidebar isOpen={sidebarOpen} />
        
        <main className="flex-1 overflow-auto">
          <div className="p-8">
            {/* Welcome Section */}
            <div className="mb-8">
              <h1 className="text-3xl font-bold text-glass-text-primary mb-6">
                Welcome back
              </h1>

              {/* Quick Actions Card */}
              <Card className="glass-elevated border-glass-border mb-8">
                <CardContent className="p-6">
                  {/* Campaign Prompt Input */}
                  <div className="mb-6">
                    <div className="relative">
                      <Input
                        placeholder="Describe your campaign idea... (e.g., 'Create a summer sale campaign for athletic wear')"
                        value={campaignPrompt}
                        onChange={(e) => setCampaignPrompt(e.target.value)}
                        className="glass-surface border-glass-border rounded-lg text-glass-text-primary placeholder:text-glass-text-muted focus:ring-2 focus:ring-[rgba(99,102,241,0.5)] focus:border-transparent pr-32 py-3 text-base"
                        onKeyPress={(e) => {
                          if (e.key === 'Enter' && campaignPrompt.trim()) {
                            handleStartCampaign();
                          }
                        }}
                      />
                      <Button 
                        onClick={handleStartCampaign}
                        disabled={!campaignPrompt.trim()}
                        className="absolute right-2 top-1/2 transform -translate-y-1/2 bg-[rgba(99,102,241,0.9)] hover:bg-[rgba(99,102,241,1)] text-white rounded-lg px-4 py-1.5 text-sm disabled:opacity-50 disabled:cursor-not-allowed"
                      >
                        <Sparkles className="w-4 h-4 mr-1" />
                        Start
                      </Button>
                    </div>
                  </div>

                  {/* Action Buttons */}
                  <div className="flex items-center space-x-4">
                    <Button 
                      variant="outline" 
                      className="glass-surface border-glass-border text-glass-text-primary hover:glass-elevated rounded-lg px-4 py-2"
                      onClick={() => setCampaignPrompt("Create a professional marketing campaign")}
                    >
                      <Sparkles className="w-4 h-4 mr-2" />
                      Campaign
                    </Button>
                    <Button 
                      variant="outline" 
                      className="glass-surface border-glass-border text-glass-text-secondary hover:glass-elevated rounded-lg px-4 py-2"
                      onClick={() => setCampaignPrompt("Build a product catalog")}
                    >
                      <FileText className="w-4 h-4 mr-2" />
                      Catalog
                    </Button>
                    <div className="flex-1"></div>
                    <Button 
                      className="bg-[rgba(99,102,241,0.9)] hover:bg-[rgba(99,102,241,1)] text-white rounded-lg px-4 py-2 text-sm"
                      onClick={() => setCampaignPrompt("Fully automate my marketing campaign creation")}
                    >
                      <Sparkles className="w-4 h-4 mr-2" />
                      Full automate
                    </Button>
                    <Link href="/campaign-generator">
                      <Button className="bg-[rgba(139,92,246,0.9)] hover:bg-[rgba(139,92,246,1)] text-white rounded-lg px-4 py-2 text-sm">
                        Generate designs
                      </Button>
                    </Link>
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* Projects Section */}
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-xl font-semibold text-glass-text-primary">
                Recent Campaigns
              </h2>
              <div className="relative w-80">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-glass-text-muted w-4 h-4" />
                <Input
                  placeholder="Search"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-10 glass-surface border-glass-border rounded-lg text-glass-text-primary placeholder:text-glass-text-muted focus:ring-2 focus:ring-[rgba(99,102,241,0.5)] focus:border-transparent"
                />
              </div>
            </div>

            {/* Projects Grid */}
            {isLoading ? (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {[...Array(4)].map((_, i) => (
                  <Card key={i} className="animate-pulse glass-surface">
                    <div className="h-40 bg-[rgba(255,255,255,0.1)] rounded-t-2xl"></div>
                    <CardContent className="p-6">
                      <div className="h-4 bg-md-sys-color-surface-container rounded mb-2"></div>
                      <div className="h-3 bg-md-sys-color-surface-container rounded w-2/3"></div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            ) : filteredCampaigns.length > 0 ? (
              <div className={viewMode === "grid" 
                ? "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6" 
                : "space-y-4"
              }>
                {filteredCampaigns.map((campaign) => (
                  <MaterialProjectCard
                    key={campaign.id}
                    campaign={campaign}
                    className={viewMode === "list" ? "flex-row" : ""}
                  />
                ))}
              </div>
            ) : (
              <Card className="surface-elevation-1 border-md-sys-color-outline-variant">
                <CardContent className="p-12 text-center">
                  <div className="w-16 h-16 mx-auto mb-4 rounded-2xl bg-md-sys-color-surface-container flex items-center justify-center">
                    <Sparkles className="w-8 h-8 text-md-sys-color-on-surface-variant" />
                  </div>
                  <h3 className="text-lg font-semibold text-md-sys-color-on-surface mb-2">
                    No campaigns yet
                  </h3>
                  <p className="text-md-sys-color-on-surface-variant mb-6">
                    Create your first marketing campaign to get started
                  </p>
                  <Link href="/campaign-generator">
                    <Button className="fab-style rounded-2xl">
                      <Plus className="w-4 h-4 mr-2" />
                      Create Campaign
                    </Button>
                  </Link>
                </CardContent>
              </Card>
            )}
          </div>
        </main>
      </div>
    </div>
  );
}
